//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 08.12.2017 1:09:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------


namespace DocStorage
{

    /// <summary>
    /// There are no comments for DocStorage.Document, DocStorage in the schema.
    /// </summary>
    public partial class Document {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Document constructor in the schema.
        /// </summary>
        public Document()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DocName in the schema.
        /// </summary>
        public virtual string DocName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Created in the schema.
        /// </summary>
        public virtual System.DateTime Created
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Path in the schema.
        /// </summary>
        public virtual string Path
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserId in the schema.
        /// </summary>
        public virtual int UserId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        public virtual User User
        {
            get;
            set;
        }
    }

}
