//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 08.12.2017 1:09:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------


namespace DocStorage
{

    /// <summary>
    /// There are no comments for DataModelMethodsExecutor in the schema.
    /// </summary>
    public partial class DataModelMethodsExecutor
    {

        private NHibernate.ISession session;

        /// <summary>
        /// There are no comments for DataModelMethodsExecutor constructor in the schema.
        /// </summary>
        public DataModelMethodsExecutor(NHibernate.ISession session)
        {
          this.session = session;
        }

    
        /// <summary>
        /// There are no comments for DropDbAndCreateUsers in the schema.
        /// </summary>
        public void DropDbAndCreateUsers()
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"DropDbAndCreateUsers");
            query.List();
        }

    
        /// <summary>
        /// There are no comments for DropDbAndCreateUsers in the schema.
        /// </summary>
        public static void DropDbAndCreateUsers(NHibernate.ISession session)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"DropDbAndCreateUsers");
            query.List();
        }

    
        /// <summary>
        /// There are no comments for AddDocument in the schema.
        /// </summary>
        public void AddDocument(string docName, System.Nullable<System.DateTime> created, string path, System.Nullable<int> userId)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"AddDocument");
            query.SetParameter(@"docName", docName);
            query.SetParameter(@"created", created);
            query.SetParameter(@"path", path);
            query.SetParameter(@"userId", userId);
            query.List();
        }

    
        /// <summary>
        /// There are no comments for AddDocument in the schema.
        /// </summary>
        public static void AddDocument(NHibernate.ISession session, string docName, System.Nullable<System.DateTime> created, string path, System.Nullable<int> userId)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"AddDocument");
            query.SetParameter(@"docName", docName);
            query.SetParameter(@"created", created);
            query.SetParameter(@"path", path);
            query.SetParameter(@"userId", userId);
            query.List();
        }
    }

}
